/**
 * Created by cshampur on 11/4/16.
 */

export const AuthMatrix = {
    'firstrun':                                 {'ops':'n', 'admin':'y'},
    'dashboard':                                {'ops':'y', 'admin':'y'},
    'networkpolicies/list':                     {'ops':'y', 'admin':'y'},
    'networkpolicies/isolation/create':         {'ops':'y', 'admin':'y'},
    'networkpolicies/isolation/details':        {'ops':'y', 'admin':'y'},
    'networkpolicies/isolation/edit':           {'ops':'y', 'admin':'y'},
    'networkpolicies/bandwidth/create':         {'ops':'y', 'admin':'y'},
    'networkpolicies/bandwidth/details':        {'ops':'y', 'admin':'y'},
    'networkpolicies/bandwidth/edit':           {'ops':'y', 'admin':'y'},
    'networkpolicies/contractgroup/create':     {'ops':'y', 'admin':'y'},
    'networkpolicies/contractgroup/details':    {'ops':'y', 'admin':'y'},
    'applicationgroups/list':                   {'ops':'y', 'admin':'y'},
    'applicationgroups/create':                 {'ops':'y', 'admin':'y'},
    'applicationgroups/details':                {'ops':'y', 'admin':'y'},
    'applicationgroups/edit':                   {'ops':'y', 'admin':'y'},
    'settings/users/list':                      {'ops':'n', 'admin':'y'},
    'settings/users/create':                    {'ops':'n', 'admin':'y'},
    'settings/users/details':                   {'ops':'n', 'admin':'y'},
    'settings/users/edit':                      {'ops':'n', 'admin':'y'},
    'settings/nodes/list':                      {'ops':'n', 'admin':'y'},
    'settings/nodes/create':                    {'ops':'n', 'admin':'y'},
    'settings/nodes/details':                   {'ops':'n', 'admin':'y'},
    'settings/nodes/edit':                      {'ops':'n', 'admin':'y'},
    'settings/authorization/list':              {'ops':'n', 'admin':'y'},
    'settings/authorization/details':           {'ops':'n', 'admin':'y'},
    'settings/authorization/create':            {'ops':'n', 'admin':'y'},
    'settings/authorization/edit':              {'ops':'n', 'admin':'y'},
    'settings/networks':                        {'ops':'n', 'admin':'y'},
    'settings/ldap':                            {'ops':'n', 'admin':'y'},
    'settings/organizations/list':              {'ops':'n', 'admin':'y'},
    'settings/organizations/create':            {'ops':'n', 'admin':'y'},
    'settings/organizations/details':           {'ops':'n', 'admin':'y'},
    'networks/list':                            {'ops':'y', 'admin':'y'},
    'networks/create':                          {'ops':'y', 'admin':'y'},
    'networks/details':                         {'ops':'y', 'admin':'y'},
    'servicelbs/list':                          {'ops':'y', 'admin':'y'},
    'servicelbs/create':                        {'ops':'y', 'admin':'y'},
    'servicelbs/details':                       {'ops':'y', 'admin':'y'},
    'appprofiles/list':                         {'ops':'y', 'admin':'y'},
    'appprofiles/create':                       {'ops':'y', 'admin':'y'},
    'appprofiles/details':                      {'ops':'y', 'admin':'y'},
    'appprofiles/edit':                         {'ops':'y', 'admin':'y'}
};